SET IDENTITY_INSERT [dbo].[Customer] ON
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (1, N'Rey', N'Seef', N'12 Kirb St', N'21674390', N'ReyS112@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (2, N'Nat', N'Tarvv', N'9 Block St', N'28947303', N'NatT@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (3, N'Wis', N'Zeel', N'5 Good St', N'23433987', N'WisZ67@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (4, N'Jeff', N'Qwejk', N'55 Devonshire St', N'21769871', N'JeffQ121@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (5, N'Cloelia', N'Mala', N'James Banks St', N'20997652', N'CloelM121@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (6, N'Tomislav', N'Jesus', N'Burnham Lodge St', N'29357693', N'TomislavJe1@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (7, N'Oluwafemi', N'Kandi', N'Embery Way St', N'32443209', N'OluwaKan0@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (8, N'Doriano', N'Mihemed', N'Spa Newydd Grove', N'21210987', N'DorianoMi88@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (9, N'Millie', N'Eustache', N'Elmete Gardens St', N'21258670', N'MillieEU1212@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (10, N'Riya', N'Harriett', N'Foundry Approach St', N'21678934', N'RiyaH15@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (11, N'Katy', N'Jen', N'13 Brains St', N'32849324', N'KatyJ1233@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (12, N'Elsie', N'Spike', N'192 Junction Road', N'21212654', N'ElsieSp1@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (13, N'Ferdy', N'Isebella', N'216 Delphi Place', N'21312312', N'FredyIse2@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (14, N'Adrianne', N'Brandy', N'90 Clark Road', N'29786212', N'AdriannB8@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (15, N'George', N'Emmett', N'132 Allington Road', N'22232398', N'GeorgeE13@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (16, N'Kayleigh', N'Norma', N'61 Avenue Road East', N'23213123', N'KayleighN0@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (17, N'Ottoline', N'Malone', N'110 Twizel-Omarama Road', N'28411169', N'OttolineMa1@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (18, N'Casimir', N'Ike
', N'214 Willock Street', N'31218640', N'CasimirI3669@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (19, N'Dylan', N'Pen', N'183 Ellis Street', N'28343478', N'DylanP33311@hotmail.com')
INSERT INTO [dbo].[Customer] ([ID], [FirstName], [LastName], [Address], [PhoneNumber], [Email]) VALUES (20, N'Crawford', N'Rocky', N'56 Bush Street', N'21345657', N'CrawfordRoc0@hotmail.com')
SET IDENTITY_INSERT [dbo].[Customer] OFF
